spring:
  profiles:
#    active: dev-test
    active: dev
#    active: online

server:
  servlet:
    context-path: /
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名
  type-aliases-package: com.ccsu.shuziyingxin.dao

dubbo:
  application: # 应用配置,用于配置当前应用信息,不管当前应用是提供者还是消费者.
    name: Consumer # 注册在注册中心的名称,唯一标识
  registry: # 注册中心配置,用于配置连接注册中心相关信息
    address: zookeeper://47.101.72.84:2181
    check: false
  protocol: # 暴露服务端口
    name: dubbo # 默认名称,勿更改
    port: 20880 # 暴露服务端口(默认为20880,修改端口,不同的服务提供者端口不能重复)
#    client: 116.62.9.40
  consumer:
    check: false
    timeout: 28000
    retries: 0
---
spring:
  profiles: dev-test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.72.84:3306/yingxin?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true
    #url: jdbc:mysql://127.0.0.1:3306/job_collection?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true
    username: root
    #password: dxp971216
    password: 123456
server:
  port: 1437

---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.72.84:3306/yingxin_online?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true
    #url: jdbc:mysql://127.0.0.1:3306/job_collection?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true
    username: root
    #password: dxp971216
    password: 123456
server:
  port: 1437

---
spring:
  profiles: online
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.72.84:3306/yingxin_online?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true
#    url: jdbc:mysql://47.101.72.84:3306/yingxin?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true
    #url: jdbc:mysql://127.0.0.1:3306/job_collection?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true
    username: root
    #password: dxp971216
    password: 123456
server:
  port: 443
  ssl:
    key-store: classpath:job.jks
    key-store-password: Jx73ifqW
    key-store-type: jks

